---
title: "Compile_pipeline_results"
format: html
editor: visual
---

liste des fichiers corrupted :

"results/RF_scores_res/RF_Rust/RF_scores_all_Rust.rds"

results/RF_scores/RF_Rust/RF_scores_all_Rust.rds"

results/VIP_scores/VIP_CIRC2009/VIP_scores_all_CIRC2009.rds

```{r}

library(data.table)
library(stringr)
library(future)
library(future.apply)
```
```{r}
imp <-readRDS("results/RF_scores_res/RF_CIRC2009/RF_scores_all_CIRC2009.rds")
```

```{r}
imp
```
```{r}
which.is.max(imp$importance)
```
```{r}
imp[21067236,]
```
```{r}
imp[importance > 0.45]
```


```{r}

filtered <- imp[SNP == "Chr16_11351593" & phenotype == "CIRC2009", .(importance, iter)]


cols <- rainbow(length(unique(filtered$iter)))
cols_iter <- cols[as.numeric(factor(filtered$iter))]

# Plot
plot(filtered$importance, col = cols_iter, pch = 16,
     xlab = "Index", ylab = "Importance", main = "Importance par itération")
legend("topright", legend = unique(filtered$iter), col = cols, pch = 16, title = "Iteration")

```



```{r}
readRDS("results/RF_all_pheno_all_snp/RF_HT2009/RF_perf_all_HT2009.rds")
```


```{r}

DIRS <- list(
  VIP_pheno = list(
    root    = "results/VIP_scores_res",
    method  = "VIP",
    context = "residuals",
    score_col = "VIP"
  ),
  RF_resid = list(
    root    = "results/VIP_scores",
    method  = "VIP",
    context = "phenotype",
    score_col = "VIP"
  ),
    RF = list(
    root    = "results/RF_scores",
    method  = "RF",
    context = "phenotype",
    score_col = "importance"
  ),
    RF = list(
    root    = "results/RF_scores_res",
    method  = "RF",
    context = "residuals",
    score_col = "importance"
  )
)

```

```{r}

DIRS <- list(
    RF = list(
    root    = "results/RF_LMM_res",
    method  = "RF",
    context = "LMM_residuals",
    score_col = "importance"
  )
)

```

```{r}
read_score_dir <- function(root, method, context, score_col) {
  print(c("traitement de >>>",root))
  pheno_dirs <- list.dirs(root, recursive = FALSE, full.names = TRUE)
  
  print(c("pour les phénotypes :",pheno_dirs))

  res <- lapply(pheno_dirs, function(d) {
    phenotype <- basename(d)
    phenotype <- str_remove(phenotype, "^(VIP|RF)_")
    
    print(c("phénotype >>>",phenotype))
    
    score_file <- list.files(
      d,
      pattern = "_scores_all_.*\\.rds$",
      full.names = TRUE
    )

    if (length(score_file) != 1) return(NULL)

    dt <- readRDS(score_file)

    if (!all(c("SNP", score_col) %in% colnames(dt))) return(NULL)

    dt[
      ,
      .(
        scores_raw = list(get(score_col)),
        n_obs      = .N,
        mean       = mean(get(score_col)),
        median     = median(get(score_col)),
        sd         = sd(get(score_col)),
        q95        = quantile(get(score_col), 0.95),
        max        = max(get(score_col))
      ),
      by = SNP
    ][
      ,
      `:=`(
        phenotype = phenotype,
        method    = method,
        context   = context
      )
    ]
  })
  print(">>> done")
  rbindlist(res, fill = TRUE)
}
```

```{r}
all_scores <- rbindlist(
  lapply(DIRS, function(x) {
    read_score_dir(
      root      = x$root,
      method    = x$method,
      context   = x$context,
      score_col = x$score_col
    )
  }),
  fill = TRUE
)
```

```{r}
setcolorder(
  all_scores,
  c(
    "SNP", "phenotype", "method", "context",
    "n_obs", "mean", "median", "sd", "q95", "max",
    "scores_raw"
  )
)

tmp_file <- tempfile(fileext = ".parquet")
write_parquet(all_scores, tmp_file)

final_file <- "results/RF_scores_LMM_res.parquet"
file.rename(tmp_file, final_file)

```
```{r}
which.is.max(all_scores$sd)
```
```{r}
all_scores[1123929]
```


```{r}
pheno_sel <- "Rust"
context_sel   <- "residuals"
method_sel    <- "RF"

dt <- all_scores[
  method   == method_sel &
  phenotype == pheno_sel &
  context  == context_sel,
  .(SNP, mean, method, context)
]
```

### Merge en parquet

```{r}
library(arrow)
```

```{r}
dt1 <- read_parquet("results/RF_scores_LMM_res.parquet", as_data_table = TRUE)
```
```{r}
dt1[,p_value := NULL]
dt1
```


```{r}

unique(dt1$phenotype)
```
```{r}
dt2
```

```{r}
dt1
```

```{r}
dt2 <- read_parquet("results/all_scores_merged.parquet", as_data_table = TRUE)
```

```{r}
dt_all <- rbind(dt2, dt1, use.names = TRUE, fill = TRUE)


tmp_file <- tempfile(fileext = ".parquet")
write_parquet(dt_all, tmp_file)

# Puis on déplace le fichier temporaire vers le chemin final
final_file <- "results/all_scores_merged_2.parquet"
file.rename(tmp_file, final_file)

```
