---
title: "LD calculation"
format: html
editor: visual
---

```{r}
library(data.table)
library(ggplot2)
library(caret)
library(nnet)
library(pls)
library(snpStats)
```

# import des datas

```{r}
data(Phenotype)
data(Genomic)
data("localisation")
```

```{r}
pheno <- as.data.table(Phenotype)
loc_df<- as.data.table(localisation)
geno<- as.data.table(Genomic)

pheno[, ID := rownames(Phenotype)]
```

```{r}
geno_mat <- as.matrix(geno)
coords <- do.call(rbind, strsplit(SNP, "_"))
chrom <- coords[,1]
pos <- as.numeric(coords[,2])
```

```{r}

compute_ld_window <- function(geno_mat, pos, window_size){
  n <- ncol(geno_mat)
  result <- list()
  for(i in seq_len(n)){
    start_pos <- pos[i]
    end_pos <- start_pos + window_size
    idx <- which(pos >= start_pos & pos <= end_pos)
    if(length(idx) > 1){
      subgeno <- as(geno_mat[, idx], "SnpMatrix")
      ldmat <- ld(subgeno, stats="R.squared",depth=1)
      result[[length(result)+1]] <- list(
        start = start_pos,
        end = end_pos,
        snps = colnames(subgeno),
        ld = ldmat
      )
    }
  }
  result
}

res <- lapply(split(seq_along(pos), chrom), function(idx){
  geno_chr <- geno_mat[, idx]
  pos_chr <- pos[idx]
  compute_ld_window(geno_chr, pos_chr, window_size = 50000)
})
```

```{r}
image(res[[1]]$D.prime, lwd=0)
```

```{r}
geno_mat <- as.matrix(geno)

storage.mode(geno_mat) <- "raw"
geno_sm <- new("SnpMatrix", geno_mat)
```

```{r}
ld.ceph <- ld(geno_sm, stats=c("D.prime", "R.squared"), depth=1000)

```

```{r}
use <- 1:100
image(ld.ceph$R.squared[use,use], lwd=0)
```

```{r}
summary(ld.ceph$D.prime[use,use])
```

```{r}
spectrum <- rainbow(10, start=0, end=1/6)[10:1]
image(ld.ceph$D.prime[use,use], lwd=0, cuts=9, col.regions=spectrum, colorkey=TRUE)
```

```{r}
lr100 <- c(68:167, 169:268)
D.prime <- ld(ceph.1mb[,168], ceph.1mb[,lr100], stats="D.prime")
where <- pos[lr100]
```
